export const DESCRIPTION_FOOTER_TEMPLATES = [
  {
    key: 'store_footer_full',
    label: 'Store Footer – Full (Badges + Table)',
    html: `<div style='font-weight:bold;color:#ffa002;font-size:20px;text-decoration:underline;'> Best-in-class | Fast, Free Shipping | 1-Day Handling | Trusted Support</div> <br> <div style='font-weight:bold;color:#ffa002;text-decoration:underline;'> We're Here Whenever You Need Us </div> <div style='color:#02a0ff;'> We take pride in delivering a smooth, worry-free shopping experience. Whether you're asking a quick question or following up after a purchase, you'll receive clear, friendly, and timely support.<br><br> All communication is handled securely through eBay's messaging system, and we typically respond within 24 hours.</div> <br> <div style='font-weight:bold;color:#ffa002;text-decoration:underline;'> Buy With Total Confidence </div> <div style='color:#02a0ff;'> Every item is carefully inspected and verified before shipping to ensure it arrives exactly as described.<br><br> Your order will ship within one business day via USPS or UPS — and shipping is always free, with no hidden costs.</div> <div style='font-weight:bold;color:#ff0000;margin-top:10px;'> ♦ Due to lighting and screen differences, actual color may vary slightly. </div> <div style='height:0.5cm;background:#ffa002;margin:15px 0;'></div> <table width='100%' cellpadding='10' cellspacing='0'> <tr align='center'> <td style='font-size:40px'>🇺🇸<br><span style='font-size:16px;font-weight:bold'>Ship from USA</span></td> <td style='font-size:40px'>🚚<br><span style='font-size:16px;font-weight:bold'>Free &amp; Fast Shipping</span></td> <td style='font-size:40px'>🛒<br><span style='font-size:16px;font-weight:bold'>30 Days Return</span></td> </tr> </table> <div style='height:0.5cm;background:#ffa002;margin:15px 0;'></div> <div style='margin-top:35px;text-align:center;font-size:18px;font-weight:bold;'> <a href='{store_url}' target='_blank' style='color:#ffa002;text-decoration:none;'> PLEASE VISIT OUR STORE TO CHECK OTHER ITEMS! </a> <p style='margin-top:10px;text-align:center;font-size:18px;color:#ffa002;font-weight:bold;'> Thank you for shopping at our store. </p> </div>`
  },
  {
    key: 'store_footer_compact',
    label: 'Store Footer – Compact (Text Only)',
    html: `<div style='font-weight:bold;color:#ffa002;font-size:18px;text-decoration:underline;'> Best-in-class | Fast, Free Shipping | 1-Day Handling | Trusted Support</div> <br> <div style='font-weight:bold;color:#ffa002;text-decoration:underline;'> We're Here Whenever You Need Us </div> <div style='color:#02a0ff;'> We take pride in delivering a smooth, worry-free shopping experience. All communication is handled securely through eBay's messaging system, and we typically respond within 24 hours.</div> <br> <div style='font-weight:bold;color:#ffa002;text-decoration:underline;'> Buy With Total Confidence </div> <div style='color:#02a0ff;'> Every item is carefully inspected before shipping. Your order ships within one business day via USPS or UPS — always free, with no hidden costs.</div> <div style='font-weight:bold;color:#ff0000;margin-top:10px;'> ♦ Due to lighting and screen differences, actual color may vary slightly. </div> <div style='height:0.5cm;background:#ffa002;margin:15px 0;'></div> <div style='margin-top:20px;text-align:center;font-size:18px;font-weight:bold;'> <a href='{store_url}' target='_blank' style='color:#ffa002;text-decoration:none;'> PLEASE VISIT OUR STORE TO CHECK OTHER ITEMS! </a> <p style='margin-top:10px;text-align:center;font-size:18px;color:#ffa002;font-weight:bold;'> Thank you for shopping at our store. </p> </div>`
  },
  {
    key: 'store_footer_minimal',
    label: 'Store Footer – Minimal (Icons + Link)',
    html: `<div style='height:0.5cm;background:#ffa002;margin:15px 0;'></div> <table width='100%' cellpadding='10' cellspacing='0'> <tr align='center'> <td style='font-size:40px'>🇺🇸<br><span style='font-size:16px;font-weight:bold'>Ship from USA</span></td> <td style='font-size:40px'>🚚<br><span style='font-size:16px;font-weight:bold'>Free &amp; Fast Shipping</span></td> <td style='font-size:40px'>🛒<br><span style='font-size:16px;font-weight:bold'>30 Days Return</span></td> </tr> </table> <div style='height:0.5cm;background:#ffa002;margin:15px 0;'></div> <div style='margin-top:20px;text-align:center;font-size:18px;font-weight:bold;'> <a href='{store_url}' target='_blank' style='color:#ffa002;text-decoration:none;'> PLEASE VISIT OUR STORE TO CHECK OTHER ITEMS! </a> <p style='margin-top:10px;text-align:center;font-size:18px;color:#ffa002;font-weight:bold;'> Thank you for shopping at our store. </p> </div>`
  }
];

export const FOOTER_SENTINEL_START = '<!-- FOOTER_TPL_START -->';
export const FOOTER_SENTINEL_END = '<!-- FOOTER_TPL_END -->';
